---

web:
  server:
    port: 5151
    workers: 1
    hostname: 0.0.0.0
    backend: pure

  template:
    views: ./app/views
    render:
      file: ::SimpleTemplater::render
      text: ::SimpleTemplater::renderString
    errors:
      - status: 500
        template: 500.html 
      - status: 500
        template: 500.html 
      - status: 404
        template: 404.html 
      - status: 401
        template: 401.html 
      - status: '*'
        template: error.html 

  public:
    assets:
      - ./app/assets
    extensions: '*' # .js,.css,.png,.jpg

  authenticator:
    secret: d00K3R$w@@rm33!$$
    url: https://authenticatorapi.com/
    enabled: true

  jwt:
    secret: 12345678910A

  credentials:
    username: test
    password: test

  filters:
    objects:
      - ::filters::FilterJson
      - ::filters::FilterHtmlTemplate
    #enter:
    #  - ::filters::filter_json_enter
    #leave: 
    #  - ::filters::filter_json_leave
    #recover: 
    #  - ::filters::filter_json_recover
  routes:
    #- path: /
    #  handler: index_handler::index
    #  roles: 
    #  methods: get
    #  
    #- path: /app/login
    #  handler: index_handler::index
    #  roles: 
    #  methods: get
    #
    #- path: /login
    #  handler: login_handler::auth
    #  roles: 
    #  methods: post
    #
    #- path: /api
    #  enter:
    #    - login_handler::auth_token
    #  roles: admin,root
    #  routes:  
    #  - path: /authenticator
    #    routes:
    #    - path: /enabled
    #      methods: get
    #      handler: api_authenticator_handler::enabled?
    #      roles: 
    #
    #    - path: /pair
    #      methods: get
    #      handler: api_authenticator_handler::pair
    #      roles: admin,root
    #- path: /ws
    #  handler: 
    #  enter: 
    #  roles: admin,root
    #  methods: get
    #  websocket: true

  websocket:
    handler: websocket_handler::handle
    handler_msg: 

datasource:
  dev:
    show_sql: false
    pool_size: 1
    database:
      db: mydb_dev
      user: root
      password: 131054
      host: localhost
      port: 3306
  test:
    show_sql: false
    pool_size: 1
    database:
      db: mydb_test
      user: root
      password: 131054
      host: localhost
      port: 3306
  prod:
    show_sql: false
    pool_size: 1
    database:
      db: mydb_prod
      user: root
      password: 131054
      host: localhost
      port: 3306
